version: '3.8'

services:
  # Base de datos MariaDB
  database:
    image: mariadb:10.11
    container_name: timebox-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: timebox_tracking
      MYSQL_USER: timebox_user
      MYSQL_PASSWORD: timebox_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./database/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
    networks:
      - timebox-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: timebox-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USER=timebox_user
      - DB_PASSWORD=timebox_password
      - DB_NAME=timebox_tracking
      - DB_CONNECTION_LIMIT=10
      - JWT_SECRET=your_jwt_secret_key_here_change_in_production
      - JWT_EXPIRES_IN=24h
      - UPLOAD_PATH=./uploads
      - MAX_FILE_SIZE=104857600
      - CORS_ORIGIN=http://localhost:4200
    volumes:
      - uploads_data:/app/uploads
    depends_on:
      database:
        condition: service_healthy
    networks:
      - timebox-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx reverse proxy (opcional)
  nginx:
    image: nginx:alpine
    container_name: timebox-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - backend
    networks:
      - timebox-network
    profiles:
      - production

volumes:
  db_data:
    driver: local
  uploads_data:
    driver: local

networks:
  timebox-network:
    driver: bridge