version: '3.8'

services:
  # Base de datos MariaDB para desarrollo
  database:
    image: mariadb:10.11
    container_name: timebox-db-dev
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: timebox_tracking
      MYSQL_USER: timebox_user
      MYSQL_PASSWORD: timebox_password
    ports:
      - "3306:3306"
    volumes:
      - db_data_dev:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./database/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
    networks:
      - timebox-network-dev
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Backend API para desarrollo
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: timebox-backend-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "9229:9229"  # Puerto para debugging
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USER=timebox_user
      - DB_PASSWORD=timebox_password
      - DB_NAME=timebox_tracking
      - DB_CONNECTION_LIMIT=10
      - JWT_SECRET=dev_jwt_secret_key
      - JWT_EXPIRES_IN=24h
      - UPLOAD_PATH=./uploads
      - MAX_FILE_SIZE=104857600
      - CORS_ORIGIN=http://localhost:4200
    volumes:
      - .:/app
      - /app/node_modules
      - uploads_data_dev:/app/uploads
    depends_on:
      database:
        condition: service_healthy
    networks:
      - timebox-network-dev
    command: npm run dev

volumes:
  db_data_dev:
    driver: local
  uploads_data_dev:
    driver: local

networks:
  timebox-network-dev:
    driver: bridge